
build windows debug:
  stage: build
  tags:
    - windows
    - dedicated
  script:
    - conan create --profile ./profiles/windows_debug ./webrtc
    - conan remote add freckled_webrtc \
        https://api.bintray.com/conan/freckled/google-webrtc
    - conan user -p "$conan_api_password" --remote freckled_webrtc freckled
    - conan upload --all --confirm --remote freckled_webrtc google-\*

build ubuntu 18.04 debug:
  stage: build
  image: registry.gitlab.com/acof/webrtc-conan/ci/build_ubuntu:18.04
  variables:
    # we can't cache files outside conan, so we set conan to a source dir
    CONAN_USER_HOME: "$CI_PROJECT_DIR/.cache"
  cache:
    key: conan
    paths:
      - .cache
  tags:
    - docker
    - dedicated
  script:
    - conan create --profile ./profiles/ubuntu1804_debug ./webrtc


